# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from beginner_tutorials/DataPckeMotor.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class DataPckeMotor(genpy.Message):
  _md5sum = "cefda5650f612b3eb74c90eb8fd012ef"
  _type = "beginner_tutorials/DataPckeMotor"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int16 titikX
int16 titikY
int16 target_sudut
int16 kecepatan_x
int16 kecepatan_y
int16 kecepatan_theta
"""
  __slots__ = ['titikX','titikY','target_sudut','kecepatan_x','kecepatan_y','kecepatan_theta']
  _slot_types = ['int16','int16','int16','int16','int16','int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       titikX,titikY,target_sudut,kecepatan_x,kecepatan_y,kecepatan_theta

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DataPckeMotor, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.titikX is None:
        self.titikX = 0
      if self.titikY is None:
        self.titikY = 0
      if self.target_sudut is None:
        self.target_sudut = 0
      if self.kecepatan_x is None:
        self.kecepatan_x = 0
      if self.kecepatan_y is None:
        self.kecepatan_y = 0
      if self.kecepatan_theta is None:
        self.kecepatan_theta = 0
    else:
      self.titikX = 0
      self.titikY = 0
      self.target_sudut = 0
      self.kecepatan_x = 0
      self.kecepatan_y = 0
      self.kecepatan_theta = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6h().pack(_x.titikX, _x.titikY, _x.target_sudut, _x.kecepatan_x, _x.kecepatan_y, _x.kecepatan_theta))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.titikX, _x.titikY, _x.target_sudut, _x.kecepatan_x, _x.kecepatan_y, _x.kecepatan_theta,) = _get_struct_6h().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6h().pack(_x.titikX, _x.titikY, _x.target_sudut, _x.kecepatan_x, _x.kecepatan_y, _x.kecepatan_theta))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.titikX, _x.titikY, _x.target_sudut, _x.kecepatan_x, _x.kecepatan_y, _x.kecepatan_theta,) = _get_struct_6h().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6h = None
def _get_struct_6h():
    global _struct_6h
    if _struct_6h is None:
        _struct_6h = struct.Struct("<6h")
    return _struct_6h
