// Generated by gencpp from file beginner_tutorials/TitikTengahBola.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_TITIKTENGAHBOLA_H
#define BEGINNER_TUTORIALS_MESSAGE_TITIKTENGAHBOLA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct TitikTengahBola_
{
  typedef TitikTengahBola_<ContainerAllocator> Type;

  TitikTengahBola_()
    : centerX(0)
    , centerY(0)  {
    }
  TitikTengahBola_(const ContainerAllocator& _alloc)
    : centerX(0)
    , centerY(0)  {
  (void)_alloc;
    }



   typedef int16_t _centerX_type;
  _centerX_type centerX;

   typedef int16_t _centerY_type;
  _centerY_type centerY;





  typedef boost::shared_ptr< ::beginner_tutorials::TitikTengahBola_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::TitikTengahBola_<ContainerAllocator> const> ConstPtr;

}; // struct TitikTengahBola_

typedef ::beginner_tutorials::TitikTengahBola_<std::allocator<void> > TitikTengahBola;

typedef boost::shared_ptr< ::beginner_tutorials::TitikTengahBola > TitikTengahBolaPtr;
typedef boost::shared_ptr< ::beginner_tutorials::TitikTengahBola const> TitikTengahBolaConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::TitikTengahBola_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::TitikTengahBola_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beginner_tutorials::TitikTengahBola_<ContainerAllocator1> & lhs, const ::beginner_tutorials::TitikTengahBola_<ContainerAllocator2> & rhs)
{
  return lhs.centerX == rhs.centerX &&
    lhs.centerY == rhs.centerY;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beginner_tutorials::TitikTengahBola_<ContainerAllocator1> & lhs, const ::beginner_tutorials::TitikTengahBola_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::TitikTengahBola_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::TitikTengahBola_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::TitikTengahBola_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::TitikTengahBola_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::TitikTengahBola_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::TitikTengahBola_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::TitikTengahBola_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cc2e74fce2d0b019ce044dd5a8d4fd1d";
  }

  static const char* value(const ::beginner_tutorials::TitikTengahBola_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcc2e74fce2d0b019ULL;
  static const uint64_t static_value2 = 0xce044dd5a8d4fd1dULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::TitikTengahBola_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/TitikTengahBola";
  }

  static const char* value(const ::beginner_tutorials::TitikTengahBola_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::TitikTengahBola_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 centerX\n"
"int16 centerY\n"
;
  }

  static const char* value(const ::beginner_tutorials::TitikTengahBola_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::TitikTengahBola_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.centerX);
      stream.next(m.centerY);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TitikTengahBola_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::TitikTengahBola_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::TitikTengahBola_<ContainerAllocator>& v)
  {
    s << indent << "centerX: ";
    Printer<int16_t>::stream(s, indent + "  ", v.centerX);
    s << indent << "centerY: ";
    Printer<int16_t>::stream(s, indent + "  ", v.centerY);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_TITIKTENGAHBOLA_H
